# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Eapolinario.GitOfTheseus
PackageVersion: 0.5.1
Installers:
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    InstallerUrl: https://github.com/eapolinario/git-of-theseus/releases/download/v0.5.1/git-of-theseus-v0.5.1-x86_64-pc-windows-msvc.zip
    InstallerSha256: 078D0F6B8873758CDF245E1DDE65A23E6A64F65B5494A4F7C61A8100E394F03D
    NestedInstallerFiles:
      - RelativeFilePath: git-of-theseus-v0.5.1-x86_64-pc-windows-msvc/git-of-theseus-analyze.exe
        PortableCommandAlias: git-of-theseus-analyze
      - RelativeFilePath: git-of-theseus-v0.5.1-x86_64-pc-windows-msvc/git-of-theseus-line-plot.exe
        PortableCommandAlias: git-of-theseus-line-plot
      - RelativeFilePath: git-of-theseus-v0.5.1-x86_64-pc-windows-msvc/git-of-theseus-stack-plot.exe
        PortableCommandAlias: git-of-theseus-stack-plot
      - RelativeFilePath: git-of-theseus-v0.5.1-x86_64-pc-windows-msvc/git-of-theseus-survival-plot.exe
        PortableCommandAlias: git-of-theseus-survival-plot
  - Architecture: arm64
    InstallerType: zip
    NestedInstallerType: portable
    InstallerUrl: https://github.com/eapolinario/git-of-theseus/releases/download/v0.5.1/git-of-theseus-v0.5.1-aarch64-pc-windows-msvc.zip
    InstallerSha256: E83F9C73E13D2C4433BEB3A669CABE0AD13343E8D6B9BE69C7112ED89A015D0F
    NestedInstallerFiles:
      - RelativeFilePath: git-of-theseus-v0.5.1-aarch64-pc-windows-msvc/git-of-theseus-analyze.exe
        PortableCommandAlias: git-of-theseus-analyze
      - RelativeFilePath: git-of-theseus-v0.5.1-aarch64-pc-windows-msvc/git-of-theseus-line-plot.exe
        PortableCommandAlias: git-of-theseus-line-plot
      - RelativeFilePath: git-of-theseus-v0.5.1-aarch64-pc-windows-msvc/git-of-theseus-stack-plot.exe
        PortableCommandAlias: git-of-theseus-stack-plot
      - RelativeFilePath: git-of-theseus-v0.5.1-aarch64-pc-windows-msvc/git-of-theseus-survival-plot.exe
        PortableCommandAlias: git-of-theseus-survival-plot
ManifestType: installer
ManifestVersion: 1.10.0
