# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json
PackageIdentifier: Eapolinario.GitOfTheseus
PackageVersion: 0.5.1
PackageLocale: en-US
Publisher: eapolinario
PublisherUrl: https://github.com/eapolinario
PublisherSupportUrl: https://github.com/eapolinario/git-of-theseus/issues
PackageName: Git of Theseus
PackageUrl: https://github.com/eapolinario/git-of-theseus
License: Apache-2.0
LicenseUrl: https://github.com/eapolinario/git-of-theseus/blob/v0.5.1/LICENSE
ShortDescription: Analyze how a Git repository grows over time.
ManifestType: defaultLocale
ManifestVersion: 1.10.0
